travel=['Chengdu','Beijing','Shanghai','Jinan','Xiamen']
print('original list: ')
print(travel)
print('\n sorted: ')
print(sorted(travel))
print('\n check: ')
print(travel)
print('\r sorted reverse')
print(sorted(travel,reverse=True))
print('\n reverse check: ')
print(travel)
print('\n reverse')
travel.reverse()
print(travel)
print('\n reverse 2')
travel.reverse()
print(travel)
print('\n sort')
travel.sort()
print(travel)
print('\n reverse sort')
travel.sort(reverse=True)
print(travel)
