# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python Project\软件综合课程设计\QtDesign_File\create_course.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_Course_Form(object):
    def setupUi(self, Create_Course_Form):
        Create_Course_Form.setObjectName("Create_Course_Form")
        Create_Course_Form.resize(336, 443)
        self.gridLayout = QtWidgets.QGridLayout(Create_Course_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(Create_Course_Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(Create_Course_Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Create_Course_Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Create_Course_Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Create_Course_Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Create_Course_Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Create_Course_Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(Create_Course_Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Create_Course_Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Create_Course_Form)
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)

        self.retranslateUi(Create_Course_Form)
        QtCore.QMetaObject.connectSlotsByName(Create_Course_Form)

    def retranslateUi(self, Create_Course_Form):
        _translate = QtCore.QCoreApplication.translate
        Create_Course_Form.setWindowTitle(_translate("Create_Course_Form", "Form"))
        self.lineEdit_3.setPlaceholderText(_translate("Create_Course_Form", "请输入课程学时"))
        self.pushButton_2.setText(_translate("Create_Course_Form", "提交"))
        self.label.setText(_translate("Create_Course_Form", "课程编号"))
        self.label_4.setText(_translate("Create_Course_Form", "开课教师工号"))
        self.label_2.setText(_translate("Create_Course_Form", "课程名称"))
        self.label_3.setText(_translate("Create_Course_Form", "课程学时"))
        self.lineEdit_2.setPlaceholderText(_translate("Create_Course_Form", "请输入课程名称"))
        self.lineEdit_4.setPlaceholderText(_translate("Create_Course_Form", "请输入开课教师工号"))
        self.pushButton.setText(_translate("Create_Course_Form", "返回"))
        self.lineEdit.setPlaceholderText(_translate("Create_Course_Form", "请输入课程编号"))
