# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python Project\软件综合课程设计\QtDesign_File\delete2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete2(object):
    def setupUi(self, Delete2):
        Delete2.setObjectName("Delete2")
        Delete2.resize(687, 350)
        self.formLayout = QtWidgets.QFormLayout(Delete2)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Delete2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Delete2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.tableWidget = QtWidgets.QTableWidget(Delete2)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget)
        self.tableWidget.setEditTriggers(self.tableWidget.NoEditTriggers)
        self.tableWidget.setColumnWidth(0,Delete2.width())

        self.retranslateUi(Delete2)
        QtCore.QMetaObject.connectSlotsByName(Delete2)

    def retranslateUi(self, Delete2):
        _translate = QtCore.QCoreApplication.translate
        Delete2.setWindowTitle(_translate("Delete2", "Form"))
        self.pushButton_2.setText(_translate("Delete2", "确认删除"))
        self.pushButton.setText(_translate("Delete2", "返回"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Delete2", "工号"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Delete2", "姓名"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Delete2", "年龄"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Delete2", "职称"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Delete2", "所在系"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Delete2", "主授课程"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Delete2", "手机号码"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Delete2", "联系地址"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Delete2", "总开课时长"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Delete2", "信息"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
