# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python Project\软件综合课程设计\QtDesign_File\modify2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modify2_Form(object):
    def setupUi(self, Modify2_Form):
        Modify2_Form.setObjectName("Modify2_Form")
        Modify2_Form.resize(336, 443)
        self.gridLayout = QtWidgets.QGridLayout(Modify2_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Modify2_Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Modify2_Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(Modify2_Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Modify2_Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(Modify2_Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(Modify2_Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(Modify2_Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(Modify2_Form)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(Modify2_Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Modify2_Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 7, 2, 1, 1)

        self.retranslateUi(Modify2_Form)
        QtCore.QMetaObject.connectSlotsByName(Modify2_Form)

    def retranslateUi(self, Modify2_Form):
        _translate = QtCore.QCoreApplication.translate
        Modify2_Form.setWindowTitle(_translate("Modify2_Form", "Form"))
        self.label.setText(_translate("Modify2_Form", "工号"))
        self.lineEdit.setPlaceholderText(_translate("Modify2_Form", "请输入工号"))
        self.label_2.setText(_translate("Modify2_Form", "姓名"))
        self.lineEdit_2.setPlaceholderText(_translate("Modify2_Form", "请输入姓名"))
        self.label_3.setText(_translate("Modify2_Form", "年龄"))
        self.lineEdit_3.setPlaceholderText(_translate("Modify2_Form", "请输入年龄"))
        self.label_4.setText(_translate("Modify2_Form", "职称"))
        self.lineEdit_4.setPlaceholderText(_translate("Modify2_Form", "请输入职称"))
        self.label_5.setText(_translate("Modify2_Form", "所在系"))
        self.lineEdit_5.setPlaceholderText(_translate("Modify2_Form", "请输入所在系"))
        self.label_6.setText(_translate("Modify2_Form", "手机号码"))
        self.lineEdit_6.setPlaceholderText(_translate("Modify2_Form", "请输入手机号码"))
        self.label_7.setText(_translate("Modify2_Form", "联系地址"))
        self.lineEdit_7.setPlaceholderText(_translate("Modify2_Form", "请输入联系地址"))
        self.pushButton_2.setText(_translate("Modify2_Form", "提交"))
        self.pushButton.setText(_translate("Modify2_Form", "返回"))
