# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python Project\软件综合课程设计\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


class Ui_Main_Menu(object):
    def setupUi(self, Main_Menu):
        Main_Menu.setObjectName("Main_Menu")
        Main_Menu.resize(259, 385)
        self.centralwidget = QtWidgets.QWidget(Main_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet
        #self.pushButton_2.clicked.connect()
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        Main_Menu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main_Menu)
        self.statusbar.setObjectName("statusbar")
        Main_Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Menu)
        QtCore.QMetaObject.connectSlotsByName(Main_Menu)

    def retranslateUi(self, Main_Menu):
        _translate = QtCore.QCoreApplication.translate
        Main_Menu.setWindowTitle(_translate("Main_Menu", "主菜单"))
        self.pushButton_2.setText(_translate("Main_Menu", "录入教师信息"))
        self.pushButton.setText(_translate("Main_Menu", "修改教师信息"))
        self.pushButton_3.setText(_translate("Main_Menu", "查询教师信息"))
        self.pushButton_5.setText(_translate("Main_Menu", "删除教师信息"))
        self.pushButton_4.setText(_translate("Main_Menu", "开设课程管理"))

class MyWindow(QMainWindow, Ui_Main_Menu):
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    myWin = MyWindow()
    myWin.show()
    sys.exit(app.exec_())